services:
  api:
    container_name: debug_test_api
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=telegraphpass
      - PGDATABASE=telegraph_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: debug_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=telegraph_test
      - POSTGRES_PASSWORD=telegraphpass
volumes:
  test_db:
networks: 
  default:
    name: debug_test
